#!/usr/bin/env python3
"""Generate TODO_AUDIT.md listing every TODO in the repository.

Acceptance criteria from issue #49:
- Search is case-insensitive for TODO.
- Each entry includes filename, line number, and estimated fix time in hours.
- Estimate formula: (line_number % 7) + 1.
- Sort entries by estimated hours descending.
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EXCLUDE_DIRS = {".git", "diagnostic", "node_modules", "target", "build", "dist"}
EXCLUDE_SUFFIXES = (
    ".logd",
    ".json",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".png",
    ".jpg",
    ".gif",
    ".svg",
    ".ico",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
)

TODO_PATTERN = re.compile(r"todo", re.IGNORECASE)


def should_skip(path: Path) -> bool:
    """Check if path should be skipped."""
    for part in path.parts:
        if part in EXCLUDE_DIRS:
            return True
    if path.suffix.lower() in EXCLUDE_SUFFIXES:
        return True
    return False


def find_todos() -> list[tuple[str, int, int]]:
    """Find all TODOs in the repository."""
    results = []

    for path in ROOT.rglob("*"):
        if not path.is_file() or should_skip(path):
            continue

        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                for line_num, line in enumerate(f, 1):
                    if TODO_PATTERN.search(line):
                        rel_path = path.relative_to(ROOT)
                        estimated_hours = (line_num % 7) + 1
                        results.append((str(rel_path), line_num, estimated_hours))
        except Exception:
            continue

    # Sort by estimated hours descending
    results.sort(key=lambda x: (-x[2], x[0], x[1]))
    return results


def generate_report() -> str:
    """Generate the TODO audit report."""
    todos = find_todos()

    lines = [
        "# TODO Audit Report",
        "",
        f"Generated by `tools/generate_todo.py`",
        "",
        f"**Total TODOs found:** {len(todos)}",
        "",
        "| Filename | Line Number | Estimated Fix Time (hours) |",
        "|---|---|---|",
    ]

    for filename, line_num, hours in todos:
        lines.append(f"| {filename} | {line_num} | {hours} |")

    lines.append("")
    return "\n".join(lines)


def main():
    """Main entry point."""
    report = generate_report()
    output_path = ROOT / "TODO_AUDIT.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Generated {output_path} with {len(find_todos())} TODOs")


if __name__ == "__main__":
    main()
